//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBCDC.Terminal {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SalvarLog {
            get {
                return ((bool)(this["SalvarLog"]));
            }
            set {
                this["SalvarLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bImprimeData {
            get {
                return ((bool)(this["bImprimeData"]));
            }
            set {
                this["bImprimeData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bImprimeHora {
            get {
                return ((bool)(this["bImprimeHora"]));
            }
            set {
                this["bImprimeHora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bImprimeMilisegundos {
            get {
                return ((bool)(this["bImprimeMilisegundos"]));
            }
            set {
                this["bImprimeMilisegundos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bRbtn {
            get {
                return ((bool)(this["bRbtn"]));
            }
            set {
                this["bRbtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbtr {
            get {
                return ((bool)(this["bRbtr"]));
            }
            set {
                this["bRbtr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbt0 {
            get {
                return ((bool)(this["bRbt0"]));
            }
            set {
                this["bRbt0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbtDecimal {
            get {
                return ((bool)(this["bRbtDecimal"]));
            }
            set {
                this["bRbtDecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"0\"")]
        public string strFinalizador {
            get {
                return ((string)(this["strFinalizador"]));
            }
            set {
                this["strFinalizador"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbt16Char {
            get {
                return ((bool)(this["bRbt16Char"]));
            }
            set {
                this["bRbt16Char"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bRbtRecAscii {
            get {
                return ((bool)(this["bRbtRecAscii"]));
            }
            set {
                this["bRbtRecAscii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbtRecHexadecimal {
            get {
                return ((bool)(this["bRbtRecHexadecimal"]));
            }
            set {
                this["bRbtRecHexadecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string PortaSerial {
            get {
                return ((string)(this["PortaSerial"]));
            }
            set {
                this["PortaSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bRbt32Char {
            get {
                return ((bool)(this["bRbt32Char"]));
            }
            set {
                this["bRbt32Char"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bQuebrarLinha {
            get {
                return ((bool)(this["bQuebrarLinha"]));
            }
            set {
                this["bQuebrarLinha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"ListaComandos.txt\"")]
        public string ArquivoListaComando {
            get {
                return ((string)(this["ArquivoListaComando"]));
            }
            set {
                this["ArquivoListaComando"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool brbtEnvAscii {
            get {
                return ((bool)(this["brbtEnvAscii"]));
            }
            set {
                this["brbtEnvAscii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool brbtEnvHexadecimal {
            get {
                return ((bool)(this["brbtEnvHexadecimal"]));
            }
            set {
                this["brbtEnvHexadecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bchkEnvLogar {
            get {
                return ((bool)(this["bchkEnvLogar"]));
            }
            set {
                this["bchkEnvLogar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bchkRecLogar {
            get {
                return ((bool)(this["bchkRecLogar"]));
            }
            set {
                this["bchkRecLogar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font fontTextos {
            get {
                return ((global::System.Drawing.Font)(this["fontTextos"]));
            }
            set {
                this["fontTextos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color colorTextos {
            get {
                return ((global::System.Drawing.Color)(this["colorTextos"]));
            }
            set {
                this["colorTextos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bEnvioAuto {
            get {
                return ((bool)(this["bEnvioAuto"]));
            }
            set {
                this["bEnvioAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public string EnvioAutoTempo {
            get {
                return ((string)(this["EnvioAutoTempo"]));
            }
            set {
                this["EnvioAutoTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strDadosEnviar {
            get {
                return ((string)(this["strDadosEnviar"]));
            }
            set {
                this["strDadosEnviar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint NumSerieSeq {
            get {
                return ((uint)(this["NumSerieSeq"]));
            }
            set {
                this["NumSerieSeq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint NumSerieDayMachine {
            get {
                return ((uint)(this["NumSerieDayMachine"]));
            }
            set {
                this["NumSerieDayMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string HwVersionMajor {
            get {
                return ((string)(this["HwVersionMajor"]));
            }
            set {
                this["HwVersionMajor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string HwVersionMinor {
            get {
                return ((string)(this["HwVersionMinor"]));
            }
            set {
                this["HwVersionMinor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1659")]
        public uint PL2303_VID {
            get {
                return ((uint)(this["PL2303_VID"]));
            }
            set {
                this["PL2303_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8963")]
        public uint PL2303_PID {
            get {
                return ((uint)(this["PL2303_PID"]));
            }
            set {
                this["PL2303_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24577")]
        public uint USERDEFINED_CDC_PID {
            get {
                return ((uint)(this["USERDEFINED_CDC_PID"]));
            }
            set {
                this["USERDEFINED_CDC_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1027")]
        public uint USERDEFINED_CDC_VID {
            get {
                return ((uint)(this["USERDEFINED_CDC_VID"]));
            }
            set {
                this["USERDEFINED_CDC_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PL2303")]
        public string usbCDCdeviceLast {
            get {
                return ((string)(this["usbCDCdeviceLast"]));
            }
            set {
                this["usbCDCdeviceLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1027")]
        public uint FT232_FT245_VID {
            get {
                return ((uint)(this["FT232_FT245_VID"]));
            }
            set {
                this["FT232_FT245_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24577")]
        public uint FT232_FT245_PID {
            get {
                return ((uint)(this["FT232_FT245_PID"]));
            }
            set {
                this["FT232_FT245_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9123")]
        public uint PL2303G_PID {
            get {
                return ((uint)(this["PL2303G_PID"]));
            }
            set {
                this["PL2303G_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1659")]
        public uint PL2303G_VID {
            get {
                return ((uint)(this["PL2303G_VID"]));
            }
            set {
                this["PL2303G_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1027")]
        public uint FT2232_VID {
            get {
                return ((uint)(this["FT2232_VID"]));
            }
            set {
                this["FT2232_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24592")]
        public uint FT2232_PID {
            get {
                return ((uint)(this["FT2232_PID"]));
            }
            set {
                this["FT2232_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1027")]
        public uint FT4232_VID {
            get {
                return ((uint)(this["FT4232_VID"]));
            }
            set {
                this["FT4232_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24593")]
        public uint FT4232_PID {
            get {
                return ((uint)(this["FT4232_PID"]));
            }
            set {
                this["FT4232_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6790")]
        public uint CH340_VID {
            get {
                return ((uint)(this["CH340_VID"]));
            }
            set {
                this["CH340_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29987")]
        public uint CH340_PID {
            get {
                return ((uint)(this["CH340_PID"]));
            }
            set {
                this["CH340_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>CH340</string>
  <string>CP210X</string>
  <string>FT232/FT245</string>
  <string>FT2232</string>
  <string>FT4232</string>
  <string>PL2303</string>
  <string>PL2303G</string>
  <string>USERDEFINED</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection usbCDCdevice {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["usbCDCdevice"]));
            }
            set {
                this["usbCDCdevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4292")]
        public uint CP210X_VID {
            get {
                return ((uint)(this["CP210X_VID"]));
            }
            set {
                this["CP210X_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public uint CP210X_PID {
            get {
                return ((uint)(this["CP210X_PID"]));
            }
            set {
                this["CP210X_PID"] = value;
            }
        }
    }
}
